version: "3.4"

services:
  jtt-webapp:
    image: "ghcr.io/devexperts/devexperts-time-tracker/jtt-webapp:build${VERSION_NUMBER}"
    container_name: jtt-webapp-build${VERSION_NUMBER}
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - WAIT_HOSTS=jtt-postgres:5432
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - VERSION=build${VERSION_NUMBER}
      - SPRING_PROFILES_ACTIVE=local,docker
      - JIRA_URL=${JIRA_URL}
      - JTT_ALLOWED_ORIGINS=http://${JTT_WEBAPP_HOST},https://${JTT_WEBAPP_HOST}
      - JTT_WEBAPP_HOST=${JTT_WEBAPP_HOST}
      - JTT_WEBAPP_PORT=80
      - JTT_USE_FIXED_RULES=false
      - POSTGRES_HOST=jtt-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=jtt
      - POSTGRES_USER=jtt
      - POSTGRES_PASSWORD=jtt
      - OAUTH_CONSUMER_KEY=${OAUTH_CONSUMER_KEY}
      - OAUTH_ACCESS_TOKEN=${OAUTH_ACCESS_TOKEN}
      - OAUTH_PRIVATE_KEY=${OAUTH_PRIVATE_KEY}
      - OAUTH_SECRET=${OAUTH_SECRET}
      - AUTHORIZATION_TYPE=OAUTH
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - dumps:/opt/dumps
      - ../log:/log
    networks:
      - backend
    expose:
      - "8080"

  jtt-proxy-ssl:
    image: nginx:latest
    container_name: jtt-proxy-ssl
    profiles: ["proxy-ssl"]
    volumes:
      - ./proxy/${FULL_CHAIN_PEM}:/etc/nginx/fullchain.pem
      - ./proxy/${PRIVATE_KEY_PEM}:/etc/nginx/privkey.pem
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend

  jtt-proxy-no-ssl:
    image: nginx:latest
    container_name: jtt-proxy-no-ssl
    profiles: ["proxy-no-ssl"]
    volumes:
      - ./proxy/nginx.no-ssl.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - backend

  jtt-postgres:
    image: "postgres:13.1"
    container_name: jtt-postgres
    environment:
      - POSTGRES_DB=jtt
      - POSTGRES_USER=jtt
      - POSTGRES_PASSWORD=jtt
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ~/jtt/postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    restart: always
    networks:
      - backend

  jtt-ui:
    image: "ghcr.io/devexperts/devexperts-time-tracker/jtt-ui:build${VERSION_NUMBER}"
    container_name: jtt-ui-build${VERSION_NUMBER}
    ports:
      - "127.0.0.1:8081:80"
      - "127.0.0.1:6006:6006"
    restart: always
    environment:
      - REACT_APP_DOMAIN=
      - REACT_APP_MANUAL=https://devexperts.github.io/devexperts-time-tracker/
      - APPLICATION_TITLE=Devexperts Time Tracker
      - BACKEND_URL=${BACKEND_URL}
    volumes:
      - ./ui-nginx:/etc/nginx/
      - ./custom_images:/usr/share/nginx/html/custom_images
    stdin_open: true
    networks:
      - backend

networks:
  backend:
    external: true

volumes:
  dumps:
    external: true